name: Generate M3U Playlist

on:
  schedule:
    - cron: '0 */6 * * *'  # Her 6 saatte bir
  workflow_dispatch:  # Manuel tetikleme için

jobs:
  generate:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Push işlemi için gerekli izin
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Tüm commit geçmişini al
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate M3U file
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: python rectv.py
    
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add rectv_full.m3u
        git diff --quiet && git diff --staged --quiet || git commit -m "Automated M3U playlist update [skip ci]"
        git push
