name: Generate M3U Playlist

on:
  schedule:
    - cron: '0 */6 * * *'  # Her 6 saatte bir
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Generate M3U file
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        python rectv.py
        echo "Oluşturulan satır sayısı: $(wc -l < rectv_full.m3u)"

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add rectv_full.m3u
        git diff --cached --quiet || git commit -m "Otomatik M3U güncellemesi [skip ci]"
        git push
